yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home'),
    path('group/<slug:slug>/', views.group_posts, name='group')
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model

from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Адрес группы')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )

    class Meta:

        ordering = ('-pub_date',)

    def __str__(self):

        return self.text[:15]

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post

TEN: int = 10


def index(request):
    posts = Post.objects.all()[:TEN]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:TEN]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/favicon.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   
   
    <title>
        {% block title %}   
          Последние обновления на сайте
        {% endblock %}
    </title>

    
  </head>
  <body>
    {% include 'includes/header.html' %} 
    <main> 
        <!-- класс py-5 создает отступы сверху и снизу блока -->


      <div class="container py-5"> 
        {% block content %}
          Контент не подвезли :(
        {% endblock %}
      </div>  

      
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>
    

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:home'  %}">
          <img src="{% static 'img/fav/favicon-16x16.png' %}">
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      
</header>
  

yatube/templates/includes/post.html
<ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>{{ post.text }}</p>  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
{{ group.title }}
{% endblock %}
  

{% block content %}
  <h1>{{ group.title }}</h1>
  {% for post in posts %}
    {% include 'includes/post.html' %}
    {% if not forloop.last %}<hr>
    {% endif %}
  {% endfor %} 
{% endblock %}
      
    

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    {% for post in posts %}
      {% include 'includes/post.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>
      {% endif %}
    {% endfor %}  
{% endblock %}
     
    